module.exports = [
  {
    "name": "takkar shaikh",
    "email": "takkar@gmail.com",
    "mobile": "7718930233",
    "carModel": "brezza",
    "password": "$2a$10$EHd1NCgVGrZ9/jrHvSE2Juz1ab4jLZDNn1ROJc1Wm8y79vKUpGzPW",
    "rating": 0,
    "startFrom": "",
    "destination": "",
    "availableSeats": 0,
    "away": 0
  },
  {
    "name": "Mirza Ghalib",
    "email": "ghalib@gmail.com",
    "mobile": "9967383950",
    "rating": 0,
    "carModel": "Scorpio",
    "password": "$2a$10$ODAZWLLPV0O4FkXNI9B66.O5CsJujC8KmYGFYRmSofTNuWN3JE5V2",
    "startFrom": "",
    "destination": "",
    "availableSeats": 0,
    "away": 0
  },
  {
    "name": "Steve Jobs",
    "email": "stevejobs@gmail.com",
    "mobile": "9967383951",
    "carModel": "Mercedes",
    "password": "$2a$10$9X/sGftdPD9s2NFu/akCGuktQes5m2HXmjTdsbrSSP3sj2QEAfaR6",
    "rating": 3,
    "startFrom": "Bangalore",
    "destination": "Ahmedabad",
    "availableSeats": 3,
    "away": 230
  },
  {
    "name": "Mir Taqi Mir",
    "email": "taqimir@gmail.com",
    "mobile": "7718930933",
    "carModel": "Classic",
    "password": "$2a$10$BiN4pLTfXhVxOZJuLvunxe5C5NQUN5wJz5ijkiGUuuyZe8lypgVKq",
    "rating": 4,
    "startFrom": "Delhi",
    "destination": "Hyderabad",
    "availableSeats": 3,
    "away": 600
  },
  {
    "name": "Faiyaz Shaikh",
    "email": "www.shtakkar@gmail.com",
    "mobile": "9967383959",
    "carModel": "Muscle",
    "password": "$2a$10$DqA49c7EKZO.KPCe3PUxouKzji0JWTr64kf1Rz2SbThRh8QOuC91q",
    "rating": 3,
    "startFrom": "Mahim",
    "destination": "Chruchgate",
    "availableSeats": 2,
    "away": 5
  },
  {
    "name": "Erich Bachman",
    "email": "erich@gmail.com",
    "mobile": "7718930733",
    "carModel": "Ford",
    "password": "$2a$10$G/6zp1/rx/dwEbbFi23zLOrUmv2UUDs2VA5oAfRPE1goyf91gSzUu",
    "rating": 1,
    "startFrom": "Nalasopara",
    "destination": "Byculla",
    "availableSeats": 3,
    "away": 40
  },
  {
    "name": "Hodor",
    "email": "hodor@gmail.com",
    "mobile": "7718930633",
    "carModel": "Hummer",
    "password": "$2a$10$vXgY.s2WDys5jvDB5ppdk.zf31rk0BpGfI1gw1ROcOtYPN.Ou8ow6",
    "rating": 5,
    "startFrom": "Allahabad",
    "destination": "Pune",
    "availableSeats": 5,
    "away": 467
  },
  {
    "name": "Tyrion Lannister",
    "email": "tyrion@gmail.com",
    "mobile": "7718930533",
    "carModel": "nano",
    "password": "$2a$10$lRGTm0Md1Jd3NIkJ8vEWT.ZD1jFnGo6MvCqleydr93UUl1TIc7P5u",
    "rating": 2,
    "startFrom": "Chennai",
    "destination": "Surat",
    "availableSeats": 3,
    "away": 660
  },
  {
    "name": "The Hound",
    "email": "hound@gmail.com",
    "mobile": "7718930433",
    "carModel": "Fortuner",
    "password": "$2a$10$RhRCmTZqlimv2xj/Y3HGNeCCzBeJdd9GtJShJenhWFd.0BFqXEGaO",
    "rating": 1,
    "startFrom": "Delhi",
    "destination": "New Delhi",
    "availableSeats": 5,
    "away": 1100
  },
  {
    "name": "Daenerys Targaryen",
    "email": "daenerys@gmail.com",
    "mobile": "7718930322",
    "carModel": "Dragon",
    "password": "$2a$10$2jKegz7I8SU4BcTe8IImK.m3SthT0TPURUz067qnGV2gm6HaKQllu",
    "rating": 4,
    "startFrom": "Santacruz",
    "destination": "Bandra",
    "availableSeats": 1,
    "away": 1
  },
  {
    "name": "Jon Snow",
    "email": "jonsnow@gmail.com",
    "mobile": "7718930200",
    "carModel": "Jaquar",
    "password": "$2a$10$rGAfLVQlhTnQhO86RavbXeqxmsVZdaAP4sR7XEAE318bmHSbn/7KK",
    "rating": 4.5,
    "startFrom": "Dadar",
    "destination": "Sion",
    "availableSeats": 0,
    "away": 12
  },
  {
    "name": "Ragnar Lothbrok",
    "email": "ragnar@gmail.com",
    "mobile": "7718930299",
    "carModel": "Fiat",
    "password": "$2a$10$ni55fJZMNHJGmw0A3nuOxejfb4f2V.okUEbQKgtxnFPLvLjIIpH4O",
    "rating": 3.5,
    "startFrom": "Borivali",
    "destination": "Marine Lines",
    "availableSeats": 3,
    "away": 44
  },
  {
    "name": "Shahrukh Khan",
    "email": "srk@gmail.com",
    "mobile": "7718930288",
    "carModel": "Mercedes",
    "password": "$2a$10$SPbZXL.Bgasuov9wJkMeduafpLxG2jcfU40qalPf0ujEQVLqZrcD.",
    "rating": 5,
    "startFrom": "Bandra",
    "destination": "Andheri",
    "availableSeats": 3,
    "away": 4
  },
  {
    "name": "Thomas Kinkade",
    "email": "kinkade@gmail.com",
    "mobile": "7718930277",
    "carModel": "BMW",
    "password": "$2a$10$PFsXQ6UH.y.Oj73RHseCn.wGszYVYOmwipjBhQ3gAnVr29oNji5I6",
    "rating": 3.5,
    "startFrom": "Dharmashala",
    "destination": "Mumbai",
    "availableSeats": 5,
    "away": 930
  },
  {
    "name": "gian",
    "email": "gian@gmail.com",
    "mobile": "7718930266",
    "carModel": "Toyoto",
    "password": "$2a$10$5BnwtGV9fgoaQM3JbGEil.YW7JDUPSpFfUx0kaAW4qUtC2.oFXnRe",
    "rating": 2,
    "startFrom": "Navi Mumbai",
    "destination": "Dharavi",
    "availableSeats": 2,
    "away": 20
  },
  {
    "name": "nobita",
    "email": "nobita@gmail.com",
    "mobile": "7718930255",
    "carModel": "honda",
    "password": "$2a$10$Th4o.NyYo77GTz9WpxNG/.coxzkBzlHnexQk73ETMkcYoUc3fFeDm",
    "rating": 3,
    "startFrom": "Navi Mumbai",
    "destination": "Mahim",
    "availableSeats": 2,
    "away": 23
  },
  {
    "name": "doraemon",
    "email": "doraemon@gmail.com",
    "mobile": "7718930244",
    "carModel": "honda",
    "password": "$2a$10$wWfvDP1moKZxX3OH.QzzwOdg1qvzZAgSaqoBuGUfvPiVp9ri4VI8y",
    "rating": 4.5,
    "startFrom": "Navi Mumbai",
    "destination": "Bandra",
    "availableSeats": 3,
    "away": 23
  },
]
